name: Node.js Pipeline

on:
  workflow_call:
    inputs:
      service-name:
        description: "Naam van de service"
        required: true
        type: string
      port:
        description: "Poort waarop de service luistert"
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: "22"
      runner:
        required: false
        type: string
        default: '["self-hosted","linux","backend1"]'

jobs:
  test:
    uses: MdBSolutions/ci-workflows/.github/workflows/test-node.yml@main
    with:
      node-version: ${{ inputs.node-version }}

  build:
    needs: test
    uses: MdBSolutions/ci-workflows/.github/workflows/build.yml@main
    with:
      service-name: ${{ inputs.service-name }}
      runner: ${{ inputs.runner }}

  startup:
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: MdBSolutions/ci-workflows/.github/workflows/startup-node.yml@main
    with:
      service-name: ${{ inputs.service-name }}
      port: ${{ inputs.port }}
      runner: ${{ inputs.runner }}
