name: Ansible Pipeline

on:
  workflow_call:
    inputs:
      playbook:
        description: "Ansible playbook bestand"
        required: false
        type: string
        default: "deploy.yml"
      runner:
        description: "GitHub Actions runner als JSON array, bijv. '[\"self-hosted\",\"linux\",\"backend1\"]'"
        required: false
        type: string
        default: '["self-hosted","linux","backend1"]'
      vault-addr:
        description: "Vault adres"
        required: false
        type: string
        default: "http://10.0.0.7:8200"

jobs:
  lint:
    runs-on: ${{ fromJson(inputs.runner) }}

    steps:
      - name: Fix workspace permissions
        if: always()
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/ansible \
            alpine chown -R $(id -u):$(id -g) /ansible

      - name: Checkout
        uses: actions/checkout@v4

      - name: ansible-lint
        run: ansible-lint ${{ inputs.playbook }}
        working-directory: ${{ github.workspace }}
